#!/bin/bash
set -e

# Is there a Git tag for the current commit?
commit=`git rev-parse HEAD`
if [ $(git describe --tags --exact-match $commit) ]; then
    # Kick off a package build.
    export PACKAGE_VERSION=$(git describe --tags --exact-match)
    rake
fi
